build:
  package:
    image: pardus/pardus-package
    volumes:
      - /packages:/packages
    commands:
      - echo "TODO lintian -i /packages/$(basename $DRONE_REPO)/*.changes"
      - apt-get update
      - apt-get install build-essential equivs devscripts
      - mkdir -p build-area
      - cd build-area
      - dpkg-source -x /packages/$(basename $DRONE_REPO)/*.dsc build-$(basename $DRONE_REPO)
      - cd build-$(basename $DRONE_REPO)
      - mk-build-deps -i -r
      - dpkg-buildpackage -b -uc
      - cd ..
      - cp  -vt /packages/$(basename $DRONE_REPO) *.udeb *.deb *.changes 2>/dev/null || true
  test:
    image: pardus/pardus-test
    volumes:
      - /packages:/packages
    commands:
      - echo "deb http://depo.pardus.org.tr/pardus onyedi main non-free" > /etc/apt/sources.list
      - apt-get update
      - apt-get install /packages/$(basename $DRONE_REPO)/*.deb
  deploy:
    image: pardus/pardus-test
    volumes:
      - /packages:/packages
    commands:
      - apt-get update
      - ls -al /packages/$(basename $DRONE_REPO)
      - echo "Done."
branches:
  - master
